# @package _global_

defaults:
  - override /data: robotwin
  - override /model: rollingwam
  - _self_

# dataloading
batch_size: 16
num_workers: 8

model:
  mot_checkpoint_mixed_attn: false

data:
  train:
    num_frames: 65  # = 4*(1 + 4*chunk_latents*(W+H) - 1) + 1; must track model.rolling W/H
    obs_offset_margin: ${eval:'${model.rolling.obs_offset_range} if ${model.rolling.obs_offset_prob} > 0 else 0'}
    skip_padding_as_possible: true
  val:
    num_frames: 65
    obs_offset_margin: ${data.train.obs_offset_margin}
    skip_padding_as_possible: true

# scheduler
lr_scheduler_type: "cosine"
learning_rate: 1e-4
num_epochs: 5
max_steps: null
log_every: 10
save_every: 2500
eval_every: 500

# training
gradient_accumulation_steps: 1
weight_decay: 1e-2
resume: null
