# @package _global_

defaults:
  - train
  - override /task: robotwin_rolling_3cam_384_1e-4
  - _self_

ckpt: null
gpu_id: 0

model:
  load_text_encoder: true
  skip_dit_load_from_pretrain: true
  action_dit_pretrained_path: null

EVALUATION:
  robotwin_root: third_party/RoboTwin
  policy_name: rollingwam_policy
  task_name: null
  task_config: demo_randomized
  instruction_type: unseen
  eval_num_episodes: 100
  output_dir: ./evaluate_results/robotwin/${hydra:runtime.choices.task}/${now:%Y%m%d_%H%M%S}

  num_inference_steps: 10  # must be divisible by model.rolling.window_blocks
  text_cfg_scale: 1.0
  negative_prompt: ""
  timing_enabled: false
  skip_get_obs_within_replan: false

  # Runtime inputs
  dataset_stats_path: null
  device: cuda

MULTIRUN:
  enabled: false
  num_gpus: 8
  max_tasks_per_gpu: 2

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
